export type PrebuiltDataVizStyleKind =
  | 'executive-scorecard'
  | 'comparison-chart'
  | 'trend-chart'
  | 'distribution-chart'
  | 'relationship-map'
  | 'status-grid'
  | 'flow-diagram'
  | 'decision-matrix'
  | 'geo-visual'
  | 'micro-chart';

export interface PrebuiltDataVizStyle {
  id: string;
  name: string;
  kind: PrebuiltDataVizStyleKind;
  description: string;
  bestFor: string[];
  preferredTemplates: string[];
  dataInputs: string[];
  visualTreatment: string;
  annotationPattern: string;
  insertionPrompt: string;
}

export const PREBUILT_DATA_VIZ_STYLES: PrebuiltDataVizStyle[] = [
  {
    id: 'viz-executive-scorecard-grid',
    name: 'Executive Scorecard Grid',
    kind: 'executive-scorecard',
    description: 'Board-ready metric grid with status, owner, trend, and action tags.',
    bestFor: ['executive review', 'quarterly performance', 'program health'],
    preferredTemplates: ['boardroom-decision-pack', 'data-observatory-pro', 'enterprise-ai-nexus'],
    dataInputs: ['metric', 'current value', 'target', 'status', 'owner', 'trend'],
    visualTreatment: 'Dense but calm card grid, navy text, subtle status dots, thin dividers, strong top-line metric hierarchy.',
    annotationPattern: 'One-line executive takeaway above the grid plus action chip per metric.',
    insertionPrompt: 'Create an Executive Scorecard Grid with metric, target, status dot, trend arrow, owner, and action chip for each card.',
  },
  {
    id: 'viz-kpi-ticker-strip',
    name: 'KPI Ticker Strip',
    kind: 'micro-chart',
    description: 'Horizontal strip of micro KPI cards with sparklines and delta chips.',
    bestFor: ['dashboard summary', 'opening proof', 'monthly update'],
    preferredTemplates: ['data-observatory-pro', 'enterprise-ai-nexus', 'product-os-launch'],
    dataInputs: ['metric label', 'value', 'delta', 'sparkline series'],
    visualTreatment: 'Compact ticker-style cards with glass backgrounds, tiny sparklines, and positive/negative delta chips.',
    annotationPattern: 'Small caption below strip: “Signals to watch”.',
    insertionPrompt: 'Insert a KPI Ticker Strip with 4-6 metric cards, each with a value, delta chip, and sparkline.',
  },
  {
    id: 'viz-waterfall-impact-bridge',
    name: 'Waterfall Impact Bridge',
    kind: 'comparison-chart',
    description: 'Waterfall chart for explaining gain/loss drivers from baseline to outcome.',
    bestFor: ['financial impact', 'efficiency gains', 'case study results'],
    preferredTemplates: ['boardroom-decision-pack', 'cinematic-case-study-system', 'data-observatory-pro'],
    dataInputs: ['baseline', 'positive drivers', 'negative drivers', 'final outcome'],
    visualTreatment: 'Stepped columns, neutral baseline/final, accent positive drivers, muted negative drivers, connector lines.',
    annotationPattern: 'Callout the largest driver and final net result.',
    insertionPrompt: 'Create a Waterfall Impact Bridge showing baseline, drivers, and final outcome with connector lines and one key driver callout.',
  },
  {
    id: 'viz-slopegraph-change-story',
    name: 'Slopegraph Change Story',
    kind: 'trend-chart',
    description: 'Before/after slopegraph showing ranking or performance changes across categories.',
    bestFor: ['before/after proof', 'rank change', 'market movement'],
    preferredTemplates: ['cinematic-case-study-system', 'boardroom-decision-pack', 'thought-leadership-editorial'],
    dataInputs: ['category', 'starting value', 'ending value'],
    visualTreatment: 'Clean two-column axis, strong highlight line, muted secondary lines, large before/after labels.',
    annotationPattern: 'Label the top mover directly on the line.',
    insertionPrompt: 'Create a Slopegraph Change Story with before and after values, muted comparison lines, and one highlighted top mover.',
  },
  {
    id: 'viz-quadrant-priority-matrix',
    name: 'Quadrant Priority Matrix',
    kind: 'decision-matrix',
    description: '2x2 matrix for impact/effort, urgency/value, or risk/readiness prioritization.',
    bestFor: ['decision making', 'roadmap prioritization', 'strategy workshop'],
    preferredTemplates: ['boardroom-decision-pack', 'immersive-workshop-lab', 'enterprise-ai-nexus'],
    dataInputs: ['item', 'x score', 'y score', 'category'],
    visualTreatment: 'Large 2x2 grid, subtle axis labels, draggable dots/cards, highlighted top-right recommendation zone.',
    annotationPattern: 'Recommendation banner attached to highest-priority quadrant.',
    insertionPrompt: 'Insert a Quadrant Priority Matrix with impact/effort axes, labeled items, and a highlighted recommendation quadrant.',
  },
  {
    id: 'viz-heatmap-risk-grid',
    name: 'Heatmap Risk Grid',
    kind: 'status-grid',
    description: 'Risk, readiness, or coverage heatmap with row/column categories and severity scale.',
    bestFor: ['risk review', 'brand QA', 'program readiness'],
    preferredTemplates: ['brand-governance-kit', 'boardroom-decision-pack', 'enterprise-ai-nexus'],
    dataInputs: ['row category', 'column category', 'severity score', 'status note'],
    visualTreatment: 'Compact grid, controlled color ramp, readable labels, status legend, not rainbow-heavy.',
    annotationPattern: 'Top-right note explains hottest cell and mitigation.',
    insertionPrompt: 'Create a Heatmap Risk Grid with rows, columns, severity color ramp, legend, and one mitigation callout.',
  },
  {
    id: 'viz-bullet-performance-bars',
    name: 'Bullet Performance Bars',
    kind: 'comparison-chart',
    description: 'Bullet charts comparing current, target, benchmark, and qualitative range.',
    bestFor: ['KPI tracking', 'goal progress', 'performance benchmark'],
    preferredTemplates: ['boardroom-decision-pack', 'data-observatory-pro', 'enterprise-ai-nexus'],
    dataInputs: ['metric label', 'current value', 'target', 'benchmark', 'range bands'],
    visualTreatment: 'Horizontal bullet bars with target marker, muted range bands, and compact metric labels.',
    annotationPattern: 'Small “above/below target” chip at right edge.',
    insertionPrompt: 'Insert Bullet Performance Bars with current bars, target markers, benchmarks, and range bands.',
  },
  {
    id: 'viz-radial-progress-cluster',
    name: 'Radial Progress Cluster',
    kind: 'executive-scorecard',
    description: 'Cluster of radial progress rings for completion, adoption, or readiness metrics.',
    bestFor: ['readiness', 'adoption', 'training progress'],
    preferredTemplates: ['immersive-workshop-lab', 'enterprise-ai-nexus', 'brand-governance-kit'],
    dataInputs: ['metric label', 'percent complete', 'status'],
    visualTreatment: 'Large central ring plus smaller support rings, minimal labels, thin neon accents on dark or clean white cards.',
    annotationPattern: 'Center statement summarizes overall readiness.',
    insertionPrompt: 'Create a Radial Progress Cluster with one primary ring and 3-4 supporting rings with labels and status chips.',
  },
  {
    id: 'viz-funnel-conversion-stack',
    name: 'Funnel Conversion Stack',
    kind: 'flow-diagram',
    description: 'Conversion funnel with stage counts, drop-off rates, and optimization notes.',
    bestFor: ['sales funnel', 'event registration', 'product adoption'],
    preferredTemplates: ['product-os-launch', 'global-launch-keynote', 'event-experience-system'],
    dataInputs: ['stage', 'count', 'conversion rate', 'drop-off reason'],
    visualTreatment: 'Stacked funnel blocks, clean stage labels, drop-off chips on the right, CTA at final stage.',
    annotationPattern: 'Callout biggest drop-off and recommended fix.',
    insertionPrompt: 'Insert a Funnel Conversion Stack with stage counts, conversion percentages, and drop-off annotations.',
  },
  {
    id: 'viz-cohort-retention-grid',
    name: 'Cohort Retention Grid',
    kind: 'status-grid',
    description: 'Cohort matrix showing retention or engagement over time with intensity shading.',
    bestFor: ['SaaS retention', 'training follow-through', 'event engagement'],
    preferredTemplates: ['product-os-launch', 'data-observatory-pro', 'immersive-workshop-lab'],
    dataInputs: ['cohort', 'period', 'retention percentage'],
    visualTreatment: 'Readable matrix, single-hue intensity scale, row labels left, period labels top, highlighted latest cohort.',
    annotationPattern: 'One insight line on strongest/weakest cohort.',
    insertionPrompt: 'Create a Cohort Retention Grid using a single-hue intensity scale and one highlighted insight row.',
  },
  {
    id: 'viz-treemap-portfolio-map',
    name: 'Treemap Portfolio Map',
    kind: 'distribution-chart',
    description: 'Treemap showing contribution, spend, capacity, or portfolio mix by category.',
    bestFor: ['budget mix', 'portfolio allocation', 'content mix'],
    preferredTemplates: ['boardroom-decision-pack', 'data-observatory-pro', 'thought-leadership-editorial'],
    dataInputs: ['category', 'value', 'group', 'status'],
    visualTreatment: 'Clean rounded rectangles, grouped color accents, label only top items, summary legend below.',
    annotationPattern: 'Top category called out with percentage contribution.',
    insertionPrompt: 'Create a Treemap Portfolio Map with grouped rectangles, top-item labels, and one contribution callout.',
  },
  {
    id: 'viz-sankey-flow-path',
    name: 'Sankey Flow Path',
    kind: 'flow-diagram',
    description: 'Flow diagram showing volume moving across stages, channels, or teams.',
    bestFor: ['process flow', 'budget flow', 'audience journey', 'workflow routing'],
    preferredTemplates: ['enterprise-ai-nexus', 'event-experience-system', 'data-observatory-pro'],
    dataInputs: ['source', 'target', 'value', 'stage'],
    visualTreatment: 'Wide curved flows, limited number of nodes, accent key flow, muted secondary flows.',
    annotationPattern: 'Highlight largest flow and bottleneck.',
    insertionPrompt: 'Create a Sankey Flow Path with source-target flows, limited nodes, and one highlighted primary flow.',
  },
  {
    id: 'viz-world-map-signal-layer',
    name: 'World Map Signal Layer',
    kind: 'geo-visual',
    description: 'Global map overlay with region signals, callout pins, and legend.',
    bestFor: ['global operations', 'event markets', 'localization coverage'],
    preferredTemplates: ['transperfect-2026', 'global-launch-keynote', 'data-observatory-pro'],
    dataInputs: ['region', 'value', 'status', 'callout'],
    visualTreatment: 'Dark or light map silhouette, glowing region pins, limited color legend, clean callout labels.',
    annotationPattern: 'Top three regions called out as small cards.',
    insertionPrompt: 'Insert a World Map Signal Layer with region pins, values, status legend, and top-three region cards.',
  },
  {
    id: 'viz-dot-plot-rank-comparison',
    name: 'Dot Plot Rank Comparison',
    kind: 'comparison-chart',
    description: 'Dot plot comparing multiple entities across a single metric with a benchmark line.',
    bestFor: ['ranked comparison', 'vendor evaluation', 'market benchmark'],
    preferredTemplates: ['boardroom-decision-pack', 'thought-leadership-editorial', 'data-observatory-pro'],
    dataInputs: ['entity', 'value', 'benchmark', 'group'],
    visualTreatment: 'Horizontal dot plot, benchmark vertical line, direct labels, highlighted recommended option.',
    annotationPattern: 'Recommendation label attached to winning dot.',
    insertionPrompt: 'Create a Dot Plot Rank Comparison with entity labels, value dots, benchmark line, and highlighted recommendation.',
  },
  {
    id: 'viz-lollipop-priority-chart',
    name: 'Lollipop Priority Chart',
    kind: 'comparison-chart',
    description: 'Readable ranked lollipop chart for priorities, impact, or survey scores.',
    bestFor: ['survey results', 'priority ranking', 'impact list'],
    preferredTemplates: ['thought-leadership-editorial', 'immersive-workshop-lab', 'boardroom-decision-pack'],
    dataInputs: ['item', 'score', 'category'],
    visualTreatment: 'Thin lines, large end dots, top three highlighted, direct value labels.',
    annotationPattern: 'Insight note under top-ranked item.',
    insertionPrompt: 'Create a Lollipop Priority Chart with ranked items, direct labels, and top-three highlights.',
  },
  {
    id: 'viz-stacked-area-momentum',
    name: 'Stacked Area Momentum Chart',
    kind: 'trend-chart',
    description: 'Stacked area trend chart showing mix and momentum over time.',
    bestFor: ['market mix', 'channel growth', 'capacity trend'],
    preferredTemplates: ['data-observatory-pro', 'product-os-launch', 'boardroom-decision-pack'],
    dataInputs: ['period', 'category values', 'total'],
    visualTreatment: 'Soft layered areas, controlled palette, end labels, one highlighted inflection point.',
    annotationPattern: 'Call out inflection point and dominant category.',
    insertionPrompt: 'Create a Stacked Area Momentum Chart with layered categories, end labels, and one inflection annotation.',
  },
  {
    id: 'viz-annotated-line-story',
    name: 'Annotated Line Story',
    kind: 'trend-chart',
    description: 'Line chart designed as a narrative with events, inflection points, and forecast band.',
    bestFor: ['trend story', 'growth narrative', 'forecast slide'],
    preferredTemplates: ['data-observatory-pro', 'thought-leadership-editorial', 'boardroom-decision-pack'],
    dataInputs: ['date', 'value', 'event annotations', 'forecast range'],
    visualTreatment: 'Single hero line, muted forecast band, numbered annotations, large takeaway title.',
    annotationPattern: 'Three numbered moments explain the trend.',
    insertionPrompt: 'Create an Annotated Line Story with a hero line, forecast band, and three numbered event annotations.',
  },
  {
    id: 'viz-donut-share-system',
    name: 'Donut Share System',
    kind: 'distribution-chart',
    description: 'Donut chart paired with ranked legend cards and a large share takeaway.',
    bestFor: ['share of spend', 'audience mix', 'portfolio distribution'],
    preferredTemplates: ['boardroom-decision-pack', 'global-launch-keynote', 'data-observatory-pro'],
    dataInputs: ['category', 'share', 'rank', 'note'],
    visualTreatment: 'Donut is secondary; ranked legend cards carry labels, values, and notes for accessibility.',
    annotationPattern: 'Center label shows the key share or total.',
    insertionPrompt: 'Create a Donut Share System with center label, ranked legend cards, and accessible direct values.',
  },
  {
    id: 'viz-network-node-map',
    name: 'Network Node Map',
    kind: 'relationship-map',
    description: 'Node-link diagram for systems, teams, content flows, or dependency maps.',
    bestFor: ['AI systems', 'workflow dependencies', 'partner ecosystem'],
    preferredTemplates: ['enterprise-ai-nexus', 'brand-governance-kit', 'event-experience-system'],
    dataInputs: ['node', 'node type', 'relationship', 'strength'],
    visualTreatment: 'Limited nodes, clear clusters, primary path highlighted, secondary relationships muted.',
    annotationPattern: 'Callout the central node and critical dependency.',
    insertionPrompt: 'Create a Network Node Map with clusters, a highlighted primary path, and central-node callout.',
  },
  {
    id: 'viz-small-multiples-sparkline-wall',
    name: 'Small Multiples Sparkline Wall',
    kind: 'micro-chart',
    description: 'Grid of small trend cards for comparing many categories without clutter.',
    bestFor: ['portfolio scan', 'regional comparison', 'category performance'],
    preferredTemplates: ['data-observatory-pro', 'transperfect-2026', 'boardroom-decision-pack'],
    dataInputs: ['category', 'sparkline series', 'latest value', 'delta'],
    visualTreatment: 'Consistent small cards, tiny sparklines, latest value, delta chip, sorted by priority.',
    annotationPattern: 'Group header explains what changed most.',
    insertionPrompt: 'Create a Small Multiples Sparkline Wall with 6-12 category cards, latest value, delta chip, and sorted order.',
  },
  {
    id: 'viz-maturity-ladder',
    name: 'Maturity Ladder',
    kind: 'decision-matrix',
    description: 'Stage-based maturity model with current state, target state, and recommended next move.',
    bestFor: ['AI maturity', 'brand maturity', 'operating model assessment'],
    preferredTemplates: ['enterprise-ai-nexus', 'brand-governance-kit', 'boardroom-decision-pack'],
    dataInputs: ['stage', 'criteria', 'current marker', 'target marker'],
    visualTreatment: 'Five-stage ladder, clear current/target markers, concise criteria under each stage.',
    annotationPattern: 'Next-step banner below target gap.',
    insertionPrompt: 'Create a Maturity Ladder with stages, current marker, target marker, and next-step banner.',
  },
];

export const getDataVizStylesForTemplate = (templateId: string) => PREBUILT_DATA_VIZ_STYLES.filter((style) => style.preferredTemplates.includes(templateId));

export const buildDataVizStylePromptBlock = (templateId: string) => {
  const styles = getDataVizStylesForTemplate(templateId);
  return [
    'PREBUILT GRAPH AND VISUAL DATA STYLES',
    `Template: ${templateId}`,
    'Use direct labeling, strong hierarchy, and readable chart geometry. Avoid decorative chartjunk and tiny labels.',
    ...styles.map((style) => `- ${style.name} [${style.kind}]: ${style.insertionPrompt}`),
  ].join('\n');
};
