import { AssetType } from '../types';

export type AssetCategory = 
  | 'branding' 
  | 'print' 
  | 'merchandise' 
  | 'digital' 
  | 'experience' 
  | 'utilities';

export interface PrintSpec {
  widthInches: number;
  heightInches: number;
  dpi: number;
  bleedInches: number;
  colorMode: 'RGB' | 'CMYK';
  fileFormat: 'PNG' | 'PDF' | 'SVG' | 'JPEG';
  notes?: string;
}

export interface AssetConfig {
  type: AssetType;
  title: string;
  description: string;
  category: AssetCategory;
  icon: string;
  printSpec?: PrintSpec;
  hasBack?: boolean;
  hasSleeve?: boolean;
  isTextBased?: boolean;
  isVideo?: boolean;
  isAudio?: boolean;
  isPresentationDeck?: boolean;
  requiresLogo?: boolean;
  aspectRatio?: string;
  pixelWidth?: number;
  pixelHeight?: number;
}

// Category metadata
export const ASSET_CATEGORIES: Record<AssetCategory, { label: string; description: string; icon: string }> = {
  branding: {
    label: 'Branding & Identity',
    description: 'Core brand elements, color palettes, and style guides',
    icon: 'Palette',
  },
  print: {
    label: 'Print & Signage',
    description: 'Banners, name tags, signage with production-ready specs',
    icon: 'Printer',
  },
  merchandise: {
    label: 'Merchandise',
    description: 'Apparel, swag, and branded merchandise mockups',
    icon: 'Shirt',
  },
  digital: {
    label: 'Digital Assets',
    description: 'Social media, email headers, and web graphics',
    icon: 'Monitor',
  },
  experience: {
    label: 'Venue & Experience',
    description: 'Stage backdrops, floor plans, and environmental graphics',
    icon: 'Building',
  },
  utilities: {
    label: 'Utilities',
    description: 'QR codes, WiFi signs, and functional assets',
    icon: 'Wrench',
  },
};

// Complete asset configuration with print specifications
export const ASSET_CONFIGS: AssetConfig[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // BRANDING & IDENTITY
  // ═══════════════════════════════════════════════════════════════════════════
  {
    type: AssetType.Palette,
    title: 'Color Palette',
    description: 'Brand colors with CMYK, Pantone, and hex values',
    category: 'branding',
    icon: 'Palette',
    isTextBased: true,
  },
  {
    type: AssetType.Logo,
    title: 'Primary Logo',
    description: 'Main event logo with clear space guidelines',
    category: 'branding',
    icon: 'Image',
    printSpec: {
      widthInches: 4,
      heightInches: 4,
      dpi: 300,
      bleedInches: 0,
      colorMode: 'CMYK',
      fileFormat: 'SVG',
    },
  },
  {
    type: AssetType.LogoMonochrome,
    title: 'Monochrome Logo',
    description: 'Single-color version for limited printing',
    category: 'branding',
    icon: 'Circle',
    printSpec: {
      widthInches: 4,
      heightInches: 4,
      dpi: 300,
      bleedInches: 0,
      colorMode: 'CMYK',
      fileFormat: 'SVG',
    },
    requiresLogo: true,
  },
  {
    type: AssetType.LogoReversed,
    title: 'Reversed Logo',
    description: 'White/light version for dark backgrounds',
    category: 'branding',
    icon: 'CircleDot',
    printSpec: {
      widthInches: 4,
      heightInches: 4,
      dpi: 300,
      bleedInches: 0,
      colorMode: 'CMYK',
      fileFormat: 'SVG',
    },
    requiresLogo: true,
  },
  {
    type: AssetType.Slogans,
    title: 'Event Slogans',
    description: 'Taglines and marketing catchphrases',
    category: 'branding',
    icon: 'Quote',
    isTextBased: true,
  },
  {
    type: AssetType.StyleGuide,
    title: 'Brand Style Guide',
    description: 'Complete brand guidelines document',
    category: 'branding',
    icon: 'BookOpen',
    isTextBased: true,
  },
  {
    type: AssetType.SeamlessPattern,
    title: 'Seamless Pattern',
    description: 'Tileable background pattern for merchandise',
    category: 'branding',
    icon: 'Grid3x3',
    pixelWidth: 1024,
    pixelHeight: 1024,
    aspectRatio: '1:1',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // PRINT & SIGNAGE
  // ═══════════════════════════════════════════════════════════════════════════
  {
    type: AssetType.NameTag,
    title: 'Name Tag (Front)',
    description: 'Attendee badge with name, company, and role',
    category: 'print',
    icon: 'CreditCard',
    hasBack: true,
    printSpec: {
      widthInches: 4,
      heightInches: 3,
      dpi: 300,
      bleedInches: 0.125,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
      notes: 'Standard badge size, compatible with Avery templates',
    },
  },
  {
    type: AssetType.NameTagBack,
    title: 'Name Tag (Back)',
    description: 'Badge reverse with schedule or sponsors',
    category: 'print',
    icon: 'CreditCard',
    printSpec: {
      widthInches: 4,
      heightInches: 3,
      dpi: 300,
      bleedInches: 0.125,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
  },
  {
    type: AssetType.Banner,
    title: 'Event Banner',
    description: 'Large format horizontal banner',
    category: 'print',
    icon: 'RectangleHorizontal',
    printSpec: {
      widthInches: 96,
      heightInches: 36,
      dpi: 150,
      bleedInches: 0.5,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
      notes: '8ft x 3ft standard banner size',
    },
    aspectRatio: '8:3',
  },
  {
    type: AssetType.EventSignage,
    title: 'General Signage',
    description: 'Multi-purpose directional signage',
    category: 'print',
    icon: 'SquareArrowRight',
    printSpec: {
      widthInches: 24,
      heightInches: 36,
      dpi: 300,
      bleedInches: 0.125,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
    aspectRatio: '2:3',
  },
  {
    type: AssetType.HangingSignage,
    title: 'Hanging Signage',
    description: 'Overhead directional or branding signs',
    category: 'print',
    icon: 'ArrowDownFromLine',
    printSpec: {
      widthInches: 36,
      heightInches: 24,
      dpi: 150,
      bleedInches: 0.25,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
    aspectRatio: '3:2',
  },
  {
    type: AssetType.OutdoorSignage,
    title: 'Outdoor Signage',
    description: 'Weather-resistant exterior signage',
    category: 'print',
    icon: 'Sun',
    printSpec: {
      widthInches: 48,
      heightInches: 72,
      dpi: 150,
      bleedInches: 0.5,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
      notes: 'UV-resistant ink recommended',
    },
    aspectRatio: '2:3',
  },
  {
    type: AssetType.DoorSignage,
    title: 'Door Signage',
    description: 'Room identification and wayfinding',
    category: 'print',
    icon: 'DoorOpen',
    printSpec: {
      widthInches: 8.5,
      heightInches: 11,
      dpi: 300,
      bleedInches: 0,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
    aspectRatio: '8.5:11',
  },
  {
    type: AssetType.EaselSignage,
    title: 'Easel Sign',
    description: 'Freestanding foam board signage',
    category: 'print',
    icon: 'Presentation',
    printSpec: {
      widthInches: 22,
      heightInches: 28,
      dpi: 300,
      bleedInches: 0.125,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
    aspectRatio: '22:28',
  },
  {
    type: AssetType.LocationSignage,
    title: 'Location Marker',
    description: 'Booth and area identification',
    category: 'print',
    icon: 'MapPin',
    printSpec: {
      widthInches: 18,
      heightInches: 24,
      dpi: 300,
      bleedInches: 0.125,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
  },
  {
    type: AssetType.RoomSignage,
    title: 'Room Signage',
    description: 'Conference room and session identifiers',
    category: 'print',
    icon: 'LayoutGrid',
    printSpec: {
      widthInches: 11,
      heightInches: 8.5,
      dpi: 300,
      bleedInches: 0,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
    aspectRatio: '11:8.5',
  },
  {
    type: AssetType.StandUpPillarBanner,
    title: 'Retractable Banner',
    description: 'Pull-up banner stand graphics',
    category: 'print',
    icon: 'PanelTop',
    printSpec: {
      widthInches: 33.5,
      heightInches: 80,
      dpi: 150,
      bleedInches: 0,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
      notes: 'Standard retractable banner size',
    },
    aspectRatio: '1:2.4',
  },
  {
    type: AssetType.FeatherFlag,
    title: 'Feather Flag',
    description: 'Outdoor feather-shaped flag banner',
    category: 'print',
    icon: 'Flag',
    printSpec: {
      widthInches: 26,
      heightInches: 112,
      dpi: 150,
      bleedInches: 0.5,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
      notes: 'Large feather flag, print both sides for double-sided',
    },
  },
  {
    type: AssetType.TeardropFlag,
    title: 'Teardrop Flag',
    description: 'Curved teardrop-shaped flag banner',
    category: 'print',
    icon: 'Droplet',
    printSpec: {
      widthInches: 27.5,
      heightInches: 66.5,
      dpi: 150,
      bleedInches: 0.5,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
  },
  {
    type: AssetType.Menu,
    title: 'Event Menu',
    description: 'Food and beverage menu card',
    category: 'print',
    icon: 'UtensilsCrossed',
    printSpec: {
      widthInches: 8.5,
      heightInches: 11,
      dpi: 300,
      bleedInches: 0.125,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
  },
  {
    type: AssetType.Folder,
    title: 'Presentation Folder',
    description: 'Branded document folder with pockets',
    category: 'print',
    icon: 'FolderOpen',
    printSpec: {
      widthInches: 18,
      heightInches: 12,
      dpi: 300,
      bleedInches: 0.125,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
      notes: 'Standard 9x12 folder with 4-inch pockets, print flat',
    },
  },
  {
    type: AssetType.ThankYouNote,
    title: 'Thank You Card',
    description: 'Post-event appreciation card',
    category: 'print',
    icon: 'Heart',
    printSpec: {
      widthInches: 5,
      heightInches: 7,
      dpi: 300,
      bleedInches: 0.125,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MERCHANDISE
  // ═══════════════════════════════════════════════════════════════════════════
  {
    type: AssetType.Tshirt,
    title: 'T-Shirt (Front)',
    description: 'Event t-shirt front design',
    category: 'merchandise',
    icon: 'Shirt',
    hasBack: true,
    hasSleeve: true,
    printSpec: {
      widthInches: 12,
      heightInches: 16,
      dpi: 300,
      bleedInches: 0,
      colorMode: 'CMYK',
      fileFormat: 'PNG',
      notes: 'DTG or screen print ready, max 8 colors for screen',
    },
  },
  {
    type: AssetType.TshirtBack,
    title: 'T-Shirt (Back)',
    description: 'Event t-shirt back design',
    category: 'merchandise',
    icon: 'Shirt',
    printSpec: {
      widthInches: 12,
      heightInches: 16,
      dpi: 300,
      bleedInches: 0,
      colorMode: 'CMYK',
      fileFormat: 'PNG',
    },
  },
  {
    type: AssetType.TshirtSleeve,
    title: 'T-Shirt (Sleeve)',
    description: 'Sleeve print design',
    category: 'merchandise',
    icon: 'Shirt',
    printSpec: {
      widthInches: 3.5,
      heightInches: 3.5,
      dpi: 300,
      bleedInches: 0,
      colorMode: 'CMYK',
      fileFormat: 'PNG',
    },
  },
  {
    type: AssetType.Hat,
    title: 'Embroidered Hat',
    description: 'Baseball cap with embroidery mockup',
    category: 'merchandise',
    icon: 'HardHat',
    printSpec: {
      widthInches: 4,
      heightInches: 2.5,
      dpi: 300,
      bleedInches: 0,
      colorMode: 'CMYK',
      fileFormat: 'PNG',
      notes: 'Max 15,000 stitches for standard embroidery',
    },
  },
  {
    type: AssetType.Lanyard,
    title: 'Lanyard',
    description: 'Neck strap with event branding',
    category: 'merchandise',
    icon: 'Ribbon',
    printSpec: {
      widthInches: 0.75,
      heightInches: 36,
      dpi: 300,
      bleedInches: 0,
      colorMode: 'CMYK',
      fileFormat: 'PNG',
      notes: 'Standard 3/4" wide lanyard, sublimation print',
    },
  },
  {
    type: AssetType.SwagBag,
    title: 'Swag Bag',
    description: 'Tote bag with event branding',
    category: 'merchandise',
    icon: 'ShoppingBag',
    printSpec: {
      widthInches: 10,
      heightInches: 12,
      dpi: 300,
      bleedInches: 0,
      colorMode: 'CMYK',
      fileFormat: 'PNG',
      notes: 'Standard canvas tote, screen print 1-2 colors',
    },
  },
  {
    type: AssetType.WaterBottle,
    title: 'Water Bottle',
    description: 'Branded water bottle wrap',
    category: 'merchandise',
    icon: 'Wine',
    printSpec: {
      widthInches: 8.25,
      heightInches: 2,
      dpi: 300,
      bleedInches: 0.0625,
      colorMode: 'CMYK',
      fileFormat: 'PNG',
      notes: 'Standard water bottle label wrap',
    },
  },
  {
    type: AssetType.StickerSheet,
    title: 'Sticker Sheet',
    description: 'Die-cut sticker collection',
    category: 'merchandise',
    icon: 'Sticker',
    printSpec: {
      widthInches: 8.5,
      heightInches: 11,
      dpi: 300,
      bleedInches: 0.125,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
      notes: 'Kiss-cut or die-cut ready',
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // DIGITAL ASSETS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    type: AssetType.SocialPost,
    title: 'Social Media Post',
    description: 'Square post for Instagram/Facebook',
    category: 'digital',
    icon: 'Share2',
    pixelWidth: 1080,
    pixelHeight: 1080,
    aspectRatio: '1:1',
  },
  {
    type: AssetType.SocialStory,
    title: 'Social Story',
    description: 'Vertical story for Instagram/TikTok',
    category: 'digital',
    icon: 'Smartphone',
    pixelWidth: 1080,
    pixelHeight: 1920,
    aspectRatio: '9:16',
  },
  {
    type: AssetType.SocialProfile,
    title: 'Social Profile Image',
    description: 'Avatar for social media accounts',
    category: 'digital',
    icon: 'User',
    pixelWidth: 400,
    pixelHeight: 400,
    aspectRatio: '1:1',
  },
  {
    type: AssetType.EmailHeader,
    title: 'Email Header',
    description: 'Banner for email campaigns',
    category: 'digital',
    icon: 'Mail',
    pixelWidth: 600,
    pixelHeight: 200,
    aspectRatio: '3:1',
  },
  {
    type: AssetType.AppIcon,
    title: 'App Icon',
    description: 'Mobile app icon set',
    category: 'digital',
    icon: 'AppWindow',
    pixelWidth: 1024,
    pixelHeight: 1024,
    aspectRatio: '1:1',
  },
  {
    type: AssetType.Favicon,
    title: 'Favicon',
    description: 'Website browser icon',
    category: 'digital',
    icon: 'Globe',
    pixelWidth: 512,
    pixelHeight: 512,
    aspectRatio: '1:1',
  },
  {
    type: AssetType.MarketingCopy,
    title: 'Marketing Copy',
    description: 'Event description and promotional text',
    category: 'digital',
    icon: 'FileText',
    isTextBased: true,
  },
  {
    type: AssetType.AgendaHighlights,
    title: 'Agenda Highlights',
    description: 'Key sessions and schedule summary',
    category: 'digital',
    icon: 'ListChecks',
    isTextBased: true,
  },
  {
    type: AssetType.Presentation,
    title: 'Presentation Deck',
    description: 'Editable slide deck for keynotes',
    category: 'digital',
    icon: 'Presentation',
    isPresentationDeck: true,
    pixelWidth: 1920,
    pixelHeight: 1080,
    aspectRatio: '16:9',
  },
  {
    type: AssetType.PresentationSlide,
    title: 'Presentation Slide',
    description: 'Single slide template',
    category: 'digital',
    icon: 'Frame',
    pixelWidth: 1920,
    pixelHeight: 1080,
    aspectRatio: '16:9',
  },
  {
    type: AssetType.VideoTeaser,
    title: 'Video Teaser',
    description: '15-30 second promotional video',
    category: 'digital',
    icon: 'Video',
    isVideo: true,
    pixelWidth: 1920,
    pixelHeight: 1080,
    aspectRatio: '16:9',
  },
  {
    type: AssetType.Soundtrack,
    title: 'Event Soundtrack',
    description: 'Background music and audio branding',
    category: 'digital',
    icon: 'Music',
    isAudio: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // VENUE & EXPERIENCE
  // ═══════════════════════════════════════════════════════════════════════════
  {
    type: AssetType.MainStageBackdrop,
    title: 'Main Stage Backdrop',
    description: 'Large format stage background',
    category: 'experience',
    icon: 'Theater',
    printSpec: {
      widthInches: 240,
      heightInches: 120,
      dpi: 72,
      bleedInches: 2,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
      notes: '20ft x 10ft, fabric or vinyl printing',
    },
    aspectRatio: '2:1',
  },
  {
    type: AssetType.BackWall,
    title: 'Backdrop Wall',
    description: 'Photo opportunity backdrop',
    category: 'experience',
    icon: 'LayoutPanelTop',
    printSpec: {
      widthInches: 96,
      heightInches: 84,
      dpi: 100,
      bleedInches: 1,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
    aspectRatio: '8:7',
  },
  {
    type: AssetType.RegistrationCounter,
    title: 'Registration Counter',
    description: 'Check-in desk front wrap',
    category: 'experience',
    icon: 'SquareUser',
    printSpec: {
      widthInches: 72,
      heightInches: 36,
      dpi: 150,
      bleedInches: 0.5,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
    aspectRatio: '2:1',
  },
  {
    type: AssetType.RegistrationBackWall,
    title: 'Registration Backdrop',
    description: 'Wall behind registration desk',
    category: 'experience',
    icon: 'PanelTopDashed',
    printSpec: {
      widthInches: 120,
      heightInches: 96,
      dpi: 100,
      bleedInches: 1,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
    aspectRatio: '5:4',
  },
  {
    type: AssetType.WelcomeCounter,
    title: 'Welcome Counter',
    description: 'Information desk wrap',
    category: 'experience',
    icon: 'Info',
    printSpec: {
      widthInches: 48,
      heightInches: 36,
      dpi: 150,
      bleedInches: 0.5,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
  },
  {
    type: AssetType.TechnologyCounter,
    title: 'Tech Demo Counter',
    description: 'Technology demonstration desk',
    category: 'experience',
    icon: 'Monitor',
    printSpec: {
      widthInches: 60,
      heightInches: 36,
      dpi: 150,
      bleedInches: 0.5,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
  },
  {
    type: AssetType.Kiosk,
    title: 'Interactive Kiosk',
    description: 'Self-service kiosk wrap design',
    category: 'experience',
    icon: 'TabletSmartphone',
    printSpec: {
      widthInches: 24,
      heightInches: 72,
      dpi: 150,
      bleedInches: 0.5,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
  },
  {
    type: AssetType.Stairs,
    title: 'Stair Graphics',
    description: 'Staircase riser branding',
    category: 'experience',
    icon: 'Footprints',
    printSpec: {
      widthInches: 48,
      heightInches: 8,
      dpi: 150,
      bleedInches: 0.25,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
      notes: 'Per stair riser, slip-resistant vinyl',
    },
  },
  {
    type: AssetType.GlassDoor,
    title: 'Glass Door Decal',
    description: 'Frosted or clear door graphics',
    category: 'experience',
    icon: 'DoorOpen',
    printSpec: {
      widthInches: 36,
      heightInches: 84,
      dpi: 150,
      bleedInches: 0,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
  },
  {
    type: AssetType.GlassDoubleDoor,
    title: 'Double Door Decal',
    description: 'Two-panel glass door graphics',
    category: 'experience',
    icon: 'Columns2',
    printSpec: {
      widthInches: 72,
      heightInches: 84,
      dpi: 150,
      bleedInches: 0,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
  },
  {
    type: AssetType.GlassRotatingDoor,
    title: 'Rotating Door Decal',
    description: 'Revolving door segment graphics',
    category: 'experience',
    icon: 'RefreshCw',
    printSpec: {
      widthInches: 30,
      heightInches: 84,
      dpi: 150,
      bleedInches: 0,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
      notes: '4 segments for standard revolving door',
    },
  },
  {
    type: AssetType.FloorPlan,
    title: 'Floor Plan',
    description: 'Venue layout with zones and flow',
    category: 'experience',
    icon: 'Map',
    pixelWidth: 2400,
    pixelHeight: 1800,
    aspectRatio: '4:3',
  },
  {
    type: AssetType.PhotorealisticShot,
    title: 'Photorealistic Mockup',
    description: 'Design placed in real-world context',
    category: 'experience',
    icon: 'Camera',
    pixelWidth: 1920,
    pixelHeight: 1080,
    aspectRatio: '16:9',
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // UTILITIES
  // ═══════════════════════════════════════════════════════════════════════════
  {
    type: AssetType.QRCode,
    title: 'QR Code',
    description: 'Scannable code with custom styling',
    category: 'utilities',
    icon: 'QrCode',
    pixelWidth: 1024,
    pixelHeight: 1024,
    aspectRatio: '1:1',
  },
  {
    type: AssetType.WifiSign,
    title: 'WiFi Sign',
    description: 'Network credentials display',
    category: 'utilities',
    icon: 'Wifi',
    printSpec: {
      widthInches: 8.5,
      heightInches: 11,
      dpi: 300,
      bleedInches: 0,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
  },
  {
    type: AssetType.RunOfShow,
    title: 'Run of Show',
    description: 'Detailed event timeline',
    category: 'utilities',
    icon: 'Clock',
    isTextBased: true,
  },
  {
    type: AssetType.LocationIntel,
    title: 'Venue Intelligence',
    description: 'Venue research and details',
    category: 'utilities',
    icon: 'Building2',
    isTextBased: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // NEW HYPER-REALISTIC EVENT ASSETS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    type: AssetType.SeatingChart,
    title: 'Seating Chart',
    description: 'Interactive table and seat assignments',
    category: 'experience',
    icon: 'LayoutGrid',
    pixelWidth: 2400,
    pixelHeight: 1800,
    aspectRatio: '4:3',
  },
  {
    type: AssetType.InvitationCard,
    title: 'Invitation Card',
    description: 'Formal event invitation design',
    category: 'print',
    icon: 'Mail',
    printSpec: {
      widthInches: 5,
      heightInches: 7,
      dpi: 300,
      bleedInches: 0.125,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
  },
  {
    type: AssetType.RSVPCard,
    title: 'RSVP Card',
    description: 'Response card for invitations',
    category: 'print',
    icon: 'Reply',
    printSpec: {
      widthInches: 5,
      heightInches: 3.5,
      dpi: 300,
      bleedInches: 0.125,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
  },
  {
    type: AssetType.ProgramBooklet,
    title: 'Program Booklet',
    description: 'Multi-page event program',
    category: 'print',
    icon: 'BookOpen',
    printSpec: {
      widthInches: 5.5,
      heightInches: 8.5,
      dpi: 300,
      bleedInches: 0.125,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
      notes: 'Half letter, saddle-stitch binding',
    },
  },
  {
    type: AssetType.PlaceCard,
    title: 'Place Card',
    description: 'Individual table seating name card',
    category: 'print',
    icon: 'UserCircle',
    printSpec: {
      widthInches: 3.5,
      heightInches: 2,
      dpi: 300,
      bleedInches: 0,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
  },
  {
    type: AssetType.TableNumber,
    title: 'Table Number',
    description: 'Table identification signage',
    category: 'print',
    icon: 'Hash',
    printSpec: {
      widthInches: 5,
      heightInches: 7,
      dpi: 300,
      bleedInches: 0,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
  },
  {
    type: AssetType.CertificateAward,
    title: 'Certificate / Award',
    description: 'Recognition and achievement certificate',
    category: 'print',
    icon: 'Award',
    printSpec: {
      widthInches: 11,
      heightInches: 8.5,
      dpi: 300,
      bleedInches: 0.125,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
  },
  {
    type: AssetType.VIPBadge,
    title: 'VIP Badge',
    description: 'Special access credential design',
    category: 'print',
    icon: 'Crown',
    printSpec: {
      widthInches: 4,
      heightInches: 3,
      dpi: 300,
      bleedInches: 0.125,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
  },
  {
    type: AssetType.ParkingPass,
    title: 'Parking Pass',
    description: 'Vehicle parking permit design',
    category: 'print',
    icon: 'Car',
    printSpec: {
      widthInches: 4,
      heightInches: 6,
      dpi: 300,
      bleedInches: 0,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
  },
  {
    type: AssetType.TicketDesign,
    title: 'Event Ticket',
    description: 'Admission ticket with QR code',
    category: 'print',
    icon: 'Ticket',
    printSpec: {
      widthInches: 5.5,
      heightInches: 2,
      dpi: 300,
      bleedInches: 0.125,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
  },
  {
    type: AssetType.WristbandDesign,
    title: 'Wristband',
    description: 'Tyvek or silicone wristband design',
    category: 'merchandise',
    icon: 'CircleDashed',
    printSpec: {
      widthInches: 10,
      heightInches: 0.75,
      dpi: 300,
      bleedInches: 0,
      colorMode: 'CMYK',
      fileFormat: 'PNG',
    },
  },
  {
    type: AssetType.TableTent,
    title: 'Table Tent',
    description: 'Freestanding tabletop display',
    category: 'print',
    icon: 'Triangle',
    printSpec: {
      widthInches: 4,
      heightInches: 6,
      dpi: 300,
      bleedInches: 0.125,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
  },
  {
    type: AssetType.CoasterDesign,
    title: 'Drink Coaster',
    description: 'Branded beverage coaster',
    category: 'merchandise',
    icon: 'Circle',
    printSpec: {
      widthInches: 4,
      heightInches: 4,
      dpi: 300,
      bleedInches: 0.125,
      colorMode: 'CMYK',
      fileFormat: 'PNG',
    },
  },
  {
    type: AssetType.PhotoBoothFrame,
    title: 'Photo Booth Frame',
    description: 'Digital frame overlay for photos',
    category: 'digital',
    icon: 'Frame',
    pixelWidth: 1200,
    pixelHeight: 1800,
    aspectRatio: '2:3',
  },
  {
    type: AssetType.PhotoBoothProps,
    title: 'Photo Booth Props',
    description: 'Printable props on sticks',
    category: 'print',
    icon: 'Glasses',
    printSpec: {
      widthInches: 11,
      heightInches: 17,
      dpi: 300,
      bleedInches: 0,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
      notes: 'Sheet of 6-8 props, cut and attach to sticks',
    },
  },
  {
    type: AssetType.CateringLabel,
    title: 'Catering Label',
    description: 'Food station identification',
    category: 'print',
    icon: 'UtensilsCrossed',
    printSpec: {
      widthInches: 4,
      heightInches: 2,
      dpi: 300,
      bleedInches: 0,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
  },
  {
    type: AssetType.DietaryCard,
    title: 'Dietary Card',
    description: 'Allergen and dietary information',
    category: 'print',
    icon: 'Salad',
    printSpec: {
      widthInches: 3,
      heightInches: 2,
      dpi: 300,
      bleedInches: 0,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
  },
  {
    type: AssetType.PressRelease,
    title: 'Press Release',
    description: 'Media announcement document',
    category: 'digital',
    icon: 'Newspaper',
    isTextBased: true,
  },
  {
    type: AssetType.MediaKit,
    title: 'Media Kit',
    description: 'Press materials and brand assets',
    category: 'digital',
    icon: 'FolderArchive',
    isTextBased: true,
  },
  {
    type: AssetType.SponsorPackage,
    title: 'Sponsor Package',
    description: 'Sponsorship tiers and benefits',
    category: 'digital',
    icon: 'Handshake',
    isTextBased: true,
  },
  {
    type: AssetType.VendorContract,
    title: 'Vendor Contract',
    description: 'Service agreement template',
    category: 'utilities',
    icon: 'FileSignature',
    isTextBased: true,
  },
  {
    type: AssetType.BudgetSheet,
    title: 'Budget Sheet',
    description: 'Event financial planning spreadsheet',
    category: 'utilities',
    icon: 'Calculator',
    isTextBased: true,
  },
  {
    type: AssetType.EventChecklist,
    title: 'Event Checklist',
    description: 'Comprehensive planning checklist',
    category: 'utilities',
    icon: 'ListTodo',
    isTextBased: true,
  },
  {
    type: AssetType.EmergencyGuide,
    title: 'Emergency Guide',
    description: 'Safety and emergency procedures',
    category: 'utilities',
    icon: 'ShieldAlert',
    isTextBased: true,
  },
  {
    type: AssetType.LinkedInBanner,
    title: 'LinkedIn Banner',
    description: 'Professional network cover image',
    category: 'digital',
    icon: 'Linkedin',
    pixelWidth: 1584,
    pixelHeight: 396,
    aspectRatio: '4:1',
  },
  {
    type: AssetType.TwitterHeader,
    title: 'Twitter/X Header',
    description: 'Social media profile header',
    category: 'digital',
    icon: 'Twitter',
    pixelWidth: 1500,
    pixelHeight: 500,
    aspectRatio: '3:1',
  },
  {
    type: AssetType.YouTubeThumbnail,
    title: 'YouTube Thumbnail',
    description: 'Video thumbnail image',
    category: 'digital',
    icon: 'Youtube',
    pixelWidth: 1280,
    pixelHeight: 720,
    aspectRatio: '16:9',
  },
  {
    type: AssetType.PodcastCover,
    title: 'Podcast Cover',
    description: 'Podcast episode artwork',
    category: 'digital',
    icon: 'Mic2',
    pixelWidth: 3000,
    pixelHeight: 3000,
    aspectRatio: '1:1',
  },
  {
    type: AssetType.AnimatedLogo,
    title: 'Animated Logo',
    description: 'Motion graphics logo reveal',
    category: 'digital',
    icon: 'Sparkles',
    isVideo: true,
    pixelWidth: 1920,
    pixelHeight: 1080,
    aspectRatio: '16:9',
  },
  {
    type: AssetType.CountdownTimer,
    title: 'Countdown Timer',
    description: 'Animated event countdown',
    category: 'digital',
    icon: 'Timer',
    isVideo: true,
    pixelWidth: 1080,
    pixelHeight: 1080,
    aspectRatio: '1:1',
  },
  {
    type: AssetType.VenueTour3D,
    title: '3D Venue Tour',
    description: 'Virtual walkthrough visualization',
    category: 'experience',
    icon: 'View',
    isVideo: true,
    pixelWidth: 1920,
    pixelHeight: 1080,
    aspectRatio: '16:9',
  },
  {
    type: AssetType.ARMarker,
    title: 'AR Marker',
    description: 'Augmented reality trigger image',
    category: 'digital',
    icon: 'Scan',
    pixelWidth: 1024,
    pixelHeight: 1024,
    aspectRatio: '1:1',
  },
  {
    type: AssetType.MatchbookDesign,
    title: 'Matchbook',
    description: 'Branded matchbook cover design',
    category: 'merchandise',
    icon: 'Flame',
    printSpec: {
      widthInches: 2.5,
      heightInches: 1.5,
      dpi: 300,
      bleedInches: 0.0625,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
      notes: 'Standard matchbook front cover',
    },
  },
  {
    type: AssetType.GiftBoxPackaging,
    title: 'Gift Box Packaging',
    description: 'Swag box and gift packaging design',
    category: 'merchandise',
    icon: 'Gift',
    printSpec: {
      widthInches: 18,
      heightInches: 14,
      dpi: 300,
      bleedInches: 0.125,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
      notes: 'Flat box template, 6x6x4 inch assembled',
    },
  },
  {
    type: AssetType.EnvelopeDesign,
    title: 'Envelope',
    description: 'Custom invitation envelope design',
    category: 'print',
    icon: 'Mail',
    printSpec: {
      widthInches: 9.5,
      heightInches: 4.125,
      dpi: 300,
      bleedInches: 0,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
      notes: 'A2 envelope size, matches 5x7 invitation',
    },
  },
  {
    type: AssetType.TableRunner,
    title: 'Table Runner',
    description: 'Branded fabric table runner',
    category: 'experience',
    icon: 'AlignHorizontalJustifyCenter',
    printSpec: {
      widthInches: 12,
      heightInches: 72,
      dpi: 150,
      bleedInches: 0.5,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
      notes: '6ft runner for standard tables',
    },
  },
  {
    type: AssetType.TableclothDesign,
    title: 'Tablecloth',
    description: 'Full table covering design',
    category: 'experience',
    icon: 'Square',
    printSpec: {
      widthInches: 90,
      heightInches: 132,
      dpi: 100,
      bleedInches: 0,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
      notes: 'Fits 6ft rectangular banquet table',
    },
  },
  {
    type: AssetType.StepAndRepeat,
    title: 'Step & Repeat Banner',
    description: 'Press wall photo backdrop',
    category: 'experience',
    icon: 'Grid3x3',
    printSpec: {
      widthInches: 96,
      heightInches: 96,
      dpi: 100,
      bleedInches: 2,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
      notes: '8ft x 8ft standard press wall',
    },
    aspectRatio: '1:1',
  },
  {
    type: AssetType.DigitalSignageLoop,
    title: 'Digital Signage Loop',
    description: 'Animated display for screens and TVs',
    category: 'digital',
    icon: 'MonitorPlay',
    isVideo: true,
    pixelWidth: 1920,
    pixelHeight: 1080,
    aspectRatio: '16:9',
  },
  {
    type: AssetType.EventAppSplash,
    title: 'Event App Splash',
    description: 'Mobile app loading screen',
    category: 'digital',
    icon: 'Smartphone',
    pixelWidth: 1284,
    pixelHeight: 2778,
    aspectRatio: '9:19.5',
  },
  {
    type: AssetType.ShuttleSignage,
    title: 'Shuttle Signage',
    description: 'Transportation pickup signage',
    category: 'print',
    icon: 'Bus',
    printSpec: {
      widthInches: 18,
      heightInches: 24,
      dpi: 300,
      bleedInches: 0.125,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
  },
  {
    type: AssetType.AccessibilitySignage,
    title: 'Accessibility Signage',
    description: 'ADA-compliant accessible route signage',
    category: 'print',
    icon: 'Accessibility',
    printSpec: {
      widthInches: 8.5,
      heightInches: 11,
      dpi: 300,
      bleedInches: 0,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
      notes: 'High contrast, Braille-ready template',
    },
  },
  {
    type: AssetType.BarMenu,
    title: 'Bar Menu',
    description: 'Cocktails and drinks menu',
    category: 'print',
    icon: 'Wine',
    printSpec: {
      widthInches: 8.5,
      heightInches: 11,
      dpi: 300,
      bleedInches: 0.125,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
  },
  {
    type: AssetType.CocktailNapkin,
    title: 'Cocktail Napkin',
    description: 'Branded beverage napkin',
    category: 'merchandise',
    icon: 'Droplets',
    printSpec: {
      widthInches: 4.75,
      heightInches: 4.75,
      dpi: 300,
      bleedInches: 0,
      colorMode: 'CMYK',
      fileFormat: 'PNG',
      notes: 'Standard cocktail napkin size',
    },
  },
  {
    type: AssetType.VIPLoungeSignage,
    title: 'VIP Lounge Signage',
    description: 'Exclusive area identification',
    category: 'print',
    icon: 'Star',
    printSpec: {
      widthInches: 18,
      heightInches: 24,
      dpi: 300,
      bleedInches: 0.125,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
  },
  {
    type: AssetType.GreenRoomSignage,
    title: 'Green Room Signage',
    description: 'Speaker/performer prep area signage',
    category: 'print',
    icon: 'DoorClosed',
    printSpec: {
      widthInches: 11,
      heightInches: 8.5,
      dpi: 300,
      bleedInches: 0,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
  },
  {
    type: AssetType.BackstagePass,
    title: 'Backstage Pass',
    description: 'All-access credential design',
    category: 'print',
    icon: 'KeyRound',
    printSpec: {
      widthInches: 4,
      heightInches: 3,
      dpi: 300,
      bleedInches: 0.125,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
  },
  {
    type: AssetType.MediaCredential,
    title: 'Media Credential',
    description: 'Press and photographer badge',
    category: 'print',
    icon: 'Camera',
    printSpec: {
      widthInches: 4,
      heightInches: 3,
      dpi: 300,
      bleedInches: 0.125,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
  },
  {
    type: AssetType.VolunteerVest,
    title: 'Volunteer Vest',
    description: 'Staff identification vest design',
    category: 'merchandise',
    icon: 'Users',
    printSpec: {
      widthInches: 12,
      heightInches: 16,
      dpi: 300,
      bleedInches: 0,
      colorMode: 'CMYK',
      fileFormat: 'PNG',
      notes: 'Front and back print areas',
    },
  },
  {
    type: AssetType.SecurityBadge,
    title: 'Security Badge',
    description: 'Security personnel credential',
    category: 'print',
    icon: 'ShieldCheck',
    printSpec: {
      widthInches: 4,
      heightInches: 3,
      dpi: 300,
      bleedInches: 0.125,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
  },
  {
    type: AssetType.LoadingDockSignage,
    title: 'Loading Dock Signage',
    description: 'Vendor and equipment access signage',
    category: 'print',
    icon: 'Truck',
    printSpec: {
      widthInches: 24,
      heightInches: 18,
      dpi: 150,
      bleedInches: 0.125,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
  },
  {
    type: AssetType.PortableBillboard,
    title: 'Portable Billboard',
    description: 'A-board or sandwich board design',
    category: 'print',
    icon: 'Signpost',
    printSpec: {
      widthInches: 24,
      heightInches: 36,
      dpi: 150,
      bleedInches: 0.25,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
  },
  {
    type: AssetType.AFrameSign,
    title: 'A-Frame Sign',
    description: 'Sidewalk sandwich board',
    category: 'print',
    icon: 'Triangle',
    printSpec: {
      widthInches: 24,
      heightInches: 36,
      dpi: 150,
      bleedInches: 0.25,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
  },
  {
    type: AssetType.WindowCling,
    title: 'Window Cling',
    description: 'Static cling window graphic',
    category: 'print',
    icon: 'AppWindow',
    printSpec: {
      widthInches: 24,
      heightInches: 36,
      dpi: 300,
      bleedInches: 0,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
  },
  {
    type: AssetType.FloorDecal,
    title: 'Floor Decal',
    description: 'Wayfinding floor graphics',
    category: 'experience',
    icon: 'Footprints',
    printSpec: {
      widthInches: 24,
      heightInches: 24,
      dpi: 150,
      bleedInches: 0.25,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
      notes: 'Slip-resistant laminate recommended',
    },
  },
  {
    type: AssetType.ElevatorWrap,
    title: 'Elevator Wrap',
    description: 'Elevator interior graphics',
    category: 'experience',
    icon: 'ArrowUpDown',
    printSpec: {
      widthInches: 72,
      heightInches: 84,
      dpi: 150,
      bleedInches: 0.5,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
  },
  {
    type: AssetType.EscalatorGraphics,
    title: 'Escalator Graphics',
    description: 'Escalator side panel graphics',
    category: 'experience',
    icon: 'Stairs',
    printSpec: {
      widthInches: 96,
      heightInches: 30,
      dpi: 150,
      bleedInches: 0.5,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
  },
  {
    type: AssetType.ColumnWrap,
    title: 'Column Wrap',
    description: 'Pillar and column branding',
    category: 'experience',
    icon: 'Cylinder',
    printSpec: {
      widthInches: 48,
      heightInches: 96,
      dpi: 150,
      bleedInches: 0.5,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
      notes: 'For 18" diameter column',
    },
  },
  {
    type: AssetType.CeilingHanger,
    title: 'Ceiling Hanger',
    description: 'Overhead hanging signs',
    category: 'experience',
    icon: 'ArrowDown',
    printSpec: {
      widthInches: 24,
      heightInches: 12,
      dpi: 150,
      bleedInches: 0.125,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
      notes: 'Double-sided print',
    },
  },
  {
    type: AssetType.BreakoutSessionSign,
    title: 'Breakout Session Sign',
    description: 'Workshop room identification',
    category: 'print',
    icon: 'Users',
    printSpec: {
      widthInches: 11,
      heightInches: 17,
      dpi: 300,
      bleedInches: 0.125,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
  },
  {
    type: AssetType.SpeakerIntroCard,
    title: 'Speaker Intro Card',
    description: 'Presenter introduction card',
    category: 'print',
    icon: 'Mic',
    printSpec: {
      widthInches: 5,
      heightInches: 7,
      dpi: 300,
      bleedInches: 0.125,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
  },
  {
    type: AssetType.SessionEvaluation,
    title: 'Session Evaluation',
    description: 'Feedback form for sessions',
    category: 'print',
    icon: 'ClipboardList',
    printSpec: {
      widthInches: 8.5,
      heightInches: 11,
      dpi: 300,
      bleedInches: 0,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
  },
  {
    type: AssetType.NetworkingBingo,
    title: 'Networking Bingo Card',
    description: 'Interactive icebreaker activity',
    category: 'print',
    icon: 'LayoutGrid',
    printSpec: {
      widthInches: 5.5,
      heightInches: 5.5,
      dpi: 300,
      bleedInches: 0,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
  },
  {
    type: AssetType.ScavengerHuntCard,
    title: 'Scavenger Hunt Card',
    description: 'Event exploration activity card',
    category: 'print',
    icon: 'Search',
    printSpec: {
      widthInches: 5.5,
      heightInches: 8.5,
      dpi: 300,
      bleedInches: 0,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
  },
  {
    type: AssetType.PollCard,
    title: 'Poll/Voting Card',
    description: 'Audience voting and polling card',
    category: 'print',
    icon: 'Vote',
    printSpec: {
      widthInches: 4,
      heightInches: 6,
      dpi: 300,
      bleedInches: 0,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
    },
  },
  {
    type: AssetType.FeedbackKiosk,
    title: 'Feedback Kiosk Screen',
    description: 'Digital feedback station UI',
    category: 'digital',
    icon: 'MessageSquare',
    pixelWidth: 1080,
    pixelHeight: 1920,
    aspectRatio: '9:16',
  },
  {
    type: AssetType.LiveStreamOverlay,
    title: 'Live Stream Overlay',
    description: 'Broadcast lower thirds and graphics',
    category: 'digital',
    icon: 'Radio',
    pixelWidth: 1920,
    pixelHeight: 1080,
    aspectRatio: '16:9',
  },
  {
    type: AssetType.HybridEventScreen,
    title: 'Hybrid Event Screen',
    description: 'Combined in-person/virtual display',
    category: 'digital',
    icon: 'MonitorSpeaker',
    pixelWidth: 1920,
    pixelHeight: 1080,
    aspectRatio: '16:9',
  },
  {
    type: AssetType.ZoomBackground,
    title: 'Zoom Background',
    description: 'Virtual meeting background',
    category: 'digital',
    icon: 'Video',
    pixelWidth: 1920,
    pixelHeight: 1080,
    aspectRatio: '16:9',
  },
  {
    type: AssetType.WebinarSlide,
    title: 'Webinar Slide',
    description: 'Virtual presentation slide template',
    category: 'digital',
    icon: 'PresentationScreen',
    pixelWidth: 1920,
    pixelHeight: 1080,
    aspectRatio: '16:9',
  },
  
  // ═══════════════════════════════════════════════════════════════════════════
  // SPONSOR ASSETS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    type: AssetType.SponsorWall,
    title: 'Sponsor Wall',
    description: 'Large format sponsor wall with logos arranged by tier (platinum, gold, silver, bronze)',
    category: 'experience',
    icon: 'LayoutGrid',
    printSpec: {
      widthInches: 120,
      heightInches: 72,
      dpi: 150,
      bleedInches: 0.5,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
      notes: '10ft x 6ft sponsor wall, logos auto-arranged by tier prominence',
    },
    aspectRatio: '5:3',
    requiresLogo: true,
  },
  {
    type: AssetType.SponsorBanner,
    title: 'Sponsor Banner',
    description: 'Horizontal banner showcasing event sponsors by tier',
    category: 'print',
    icon: 'RectangleHorizontal',
    printSpec: {
      widthInches: 96,
      heightInches: 24,
      dpi: 150,
      bleedInches: 0.5,
      colorMode: 'CMYK',
      fileFormat: 'PDF',
      notes: '8ft x 2ft sponsor banner, tier-based logo sizing',
    },
    aspectRatio: '4:1',
    requiresLogo: true,
  },
  {
    type: AssetType.SponsorGrid,
    title: 'Sponsor Grid',
    description: 'Digital sponsor showcase for screens and presentations',
    category: 'digital',
    icon: 'Grid3x3',
    pixelWidth: 1920,
    pixelHeight: 1080,
    aspectRatio: '16:9',
    requiresLogo: true,
  },
];

// Helper functions
export const getAssetConfig = (type: AssetType): AssetConfig | undefined => {
  return ASSET_CONFIGS.find(config => config.type === type);
};

export const getAssetsByCategory = (category: AssetCategory): AssetConfig[] => {
  return ASSET_CONFIGS.filter(config => config.category === category);
};

export const getCategoryForAsset = (type: AssetType): AssetCategory | undefined => {
  return ASSET_CONFIGS.find(config => config.type === type)?.category;
};

export const getPrintReadyAssets = (): AssetConfig[] => {
  return ASSET_CONFIGS.filter(config => config.printSpec);
};

export const getDigitalAssets = (): AssetConfig[] => {
  return ASSET_CONFIGS.filter(config => !config.printSpec && !config.isTextBased);
};

export const getTextBasedAssets = (): AssetConfig[] => {
  return ASSET_CONFIGS.filter(config => config.isTextBased);
};

// Default recommended assets for quick start
export const DEFAULT_QUICK_START_ASSETS: AssetType[] = [
  AssetType.Palette,
  AssetType.Slogans,
  AssetType.SocialPost,
  AssetType.SocialStory,
  AssetType.NameTag,
  AssetType.Banner,
  AssetType.Tshirt,
  AssetType.Lanyard,
  AssetType.WifiSign,
  AssetType.EmailHeader,
];

// Full suite of assets for comprehensive generation
export const FULL_SUITE_ASSETS: AssetType[] = ASSET_CONFIGS
  .filter(c => c.type !== AssetType.Logo && 
              c.type !== AssetType.NameTagBack && 
              c.type !== AssetType.TshirtBack && 
              c.type !== AssetType.TshirtSleeve)
  .map(c => c.type);
