// Cutting-edge presentation template pack 2 — asset-rich pages with drag/drop slots

import { EditableTemplate, TemplateField } from '@/types/editableTemplate.types';
import { AssetType } from '@/types';

const createPixelDimensions = (w: number, h: number) => ({
  widthInches: w / 72,
  heightInches: h / 72,
  widthPx: w,
  heightPx: h,
  bleedInches: 0,
  safeZoneInches: 0,
  orientation: (w > h ? 'landscape' : h > w ? 'portrait' : 'square') as 'portrait' | 'landscape' | 'square',
});

const field = (
  id: string,
  type: TemplateField['type'],
  name: string,
  position: TemplateField['position'],
  options: Partial<Omit<TemplateField, 'id' | 'name' | 'type' | 'position'>> = {},
): TemplateField => ({
  id,
  name,
  type,
  position,
  style: {
    fontFamily: 'Inter',
    fontSize: 14,
    fontWeight: 'normal',
    color: '#ffffff',
    ...options.style,
  },
  ...options,
});

const text = (id: string, name: string, position: TemplateField['position'], options: Partial<Omit<TemplateField, 'id' | 'name' | 'type' | 'position'>> = {}) => field(id, 'text', name, position, options);
const image = (id: string, name: string, position: TemplateField['position'], options: Partial<Omit<TemplateField, 'id' | 'name' | 'type' | 'position'>> = {}) => field(id, 'image', name, position, { acceptedFormats: ['jpg', 'png', 'webp'], style: { objectFit: 'cover', borderRadius: 18, ...options.style }, ...options });
const logo = (id: string, name: string, position: TemplateField['position'], options: Partial<Omit<TemplateField, 'id' | 'name' | 'type' | 'position'>> = {}) => field(id, 'logo', name, position, { acceptedFormats: ['png', 'svg'], style: { objectFit: 'contain', ...options.style }, ...options });
const icon = (id: string, name: string, position: TemplateField['position'], options: Partial<Omit<TemplateField, 'id' | 'name' | 'type' | 'position'>> = {}) => field(id, 'icon', name, position, { placeholder: 'Drop icon / SVG', acceptedFormats: ['svg', 'png'], style: { objectFit: 'contain', ...options.style }, ...options });
const qr = (id: string, name: string, position: TemplateField['position'], options: Partial<Omit<TemplateField, 'id' | 'name' | 'type' | 'position'>> = {}) => field(id, 'qrcode', name, position, { placeholder: 'Drop QR / enter URL', style: { backgroundColor: '#ffffff', borderRadius: 12, ...options.style }, ...options });
const divider = (id: string, name: string, position: TemplateField['position'], color: string): TemplateField => field(id, 'divider', name, position, { style: { backgroundColor: color } });

const SLIDE_16_9 = createPixelDimensions(1920, 1080);

export const CUTTING_EDGE_PRESENTATION_TEMPLATE_PACK_2: EditableTemplate[] = [
  {
    id: 'pres-immersive-product-showcase',
    name: 'Immersive Product Showcase',
    description: 'Hero product layout with drag-and-drop product render, supporting detail images, feature icons, and CTA QR.',
    assetType: AssetType.PresentationSlide,
    category: 'premium',
    background: { type: 'gradient', value: 'radial-gradient(circle at 72% 42%, rgba(19,157,216,0.42), transparent 35%), linear-gradient(135deg, #03002C 0%, #08143F 45%, #10183A 100%)' },
    dimensions: SLIDE_16_9,
    fields: [
      logo('brand-logo', 'Brand Logo', { x: 5, y: 5, width: 10, height: 7 }),
      text('eyebrow', 'Eyebrow', { x: 6, y: 16, width: 34, height: 5 }, { placeholder: 'PRODUCT LAUNCH', style: { fontSize: 13, fontWeight: 'bold', letterSpacing: 4, color: '#A1F9F9' } }),
      text('title', 'Product Name', { x: 6, y: 25, width: 42, height: 16 }, { placeholder: 'A smarter way to launch globally', required: true, style: { fontSize: 48, fontWeight: 'bold', lineHeight: 1.05 } }),
      text('body', 'Product Story', { x: 6, y: 47, width: 36, height: 16 }, { placeholder: 'Describe the product promise, the audience need, and the primary differentiator in one crisp paragraph.', style: { fontSize: 18, lineHeight: 1.5, color: 'rgba(255,255,255,0.72)' } }),
      image('product-render', 'Drag Product Render', { x: 50, y: 15, width: 39, height: 48 }, { placeholder: 'Drop product render / device mockup here', aspectRatio: 1.45, group: 'drag-drop-assets' }),
      image('detail-shot-1', 'Detail Image 1', { x: 50, y: 70, width: 12, height: 14 }, { placeholder: 'Drop detail image', aspectRatio: 1, group: 'drag-drop-assets' }),
      image('detail-shot-2', 'Detail Image 2', { x: 65, y: 70, width: 12, height: 14 }, { placeholder: 'Drop detail image', aspectRatio: 1, group: 'drag-drop-assets' }),
      image('detail-shot-3', 'Detail Image 3', { x: 80, y: 70, width: 12, height: 14 }, { placeholder: 'Drop detail image', aspectRatio: 1, group: 'drag-drop-assets' }),
      icon('feature-icon-1', 'Feature Icon 1', { x: 6, y: 73, width: 4, height: 5 }, { group: 'drag-drop-assets' }),
      text('feature-1', 'Feature 1', { x: 11, y: 73, width: 22, height: 5 }, { placeholder: 'Brand-safe output', style: { fontSize: 15, fontWeight: 'bold' } }),
      qr('cta-qr', 'CTA QR Code', { x: 37, y: 73, width: 8, height: 12 }, { group: 'drag-drop-assets' }),
    ],
    defaultFonts: { heading: 'Inter', body: 'Inter' },
    defaultColors: { primary: '#139DD8', secondary: '#003B71', accent: '#A1F9F9', text: '#ffffff', background: '#03002C' },
    tags: ['presentation', 'product', 'launch', 'drag-drop', 'assets', 'premium'],
    colorMode: 'RGB',
    dpi: 72,
    isPremium: true,
    isSystemTemplate: true,
  },
  {
    id: 'pres-global-event-opener',
    name: 'Global Event Opener',
    description: 'High-energy event opener with venue image slot, sponsor logo rail, event metadata, and hero CTA.',
    assetType: AssetType.PresentationSlide,
    category: 'premium',
    background: { type: 'gradient', value: 'linear-gradient(120deg, #001C3D 0%, #003B71 42%, #03002C 100%)' },
    dimensions: SLIDE_16_9,
    fields: [
      image('venue-image', 'Drag Venue / City Image', { x: 49, y: 0, width: 51, height: 100 }, { placeholder: 'Drop city, venue, or event image', group: 'drag-drop-assets' }),
      logo('event-logo', 'Event Logo', { x: 6, y: 7, width: 18, height: 12 }),
      text('event-type', 'Event Type', { x: 6, y: 25, width: 34, height: 5 }, { placeholder: 'GLOBAL SUMMIT 2026', style: { fontSize: 14, fontWeight: 'bold', letterSpacing: 4, color: '#A1F9F9' } }),
      text('title', 'Event Title', { x: 6, y: 34, width: 38, height: 20 }, { placeholder: 'Where global teams move faster', required: true, style: { fontSize: 54, fontWeight: 'bold', lineHeight: 0.98 } }),
      text('date-location', 'Date + Location', { x: 6, y: 61, width: 34, height: 7 }, { placeholder: 'MAY 18–20 • SAN JUAN', style: { fontSize: 18, fontWeight: 'bold', color: '#A1F9F9' } }),
      logo('sponsor-1', 'Sponsor Logo 1', { x: 6, y: 82, width: 10, height: 6 }, { group: 'drag-drop-assets' }),
      logo('sponsor-2', 'Sponsor Logo 2', { x: 18, y: 82, width: 10, height: 6 }, { group: 'drag-drop-assets' }),
      logo('sponsor-3', 'Sponsor Logo 3', { x: 30, y: 82, width: 10, height: 6 }, { group: 'drag-drop-assets' }),
    ],
    defaultFonts: { heading: 'Inter', body: 'Inter' },
    defaultColors: { primary: '#139DD8', secondary: '#003B71', accent: '#A1F9F9', text: '#ffffff', background: '#001C3D' },
    tags: ['presentation', 'event', 'opener', 'venue', 'sponsor', 'drag-drop', 'premium'],
    colorMode: 'RGB',
    dpi: 72,
    isPremium: true,
    isSystemTemplate: true,
  },
  {
    id: 'pres-portfolio-gallery-wall',
    name: 'Portfolio Gallery Wall',
    description: 'Visual gallery slide with six draggable image panels and a branded narrative sidebar.',
    assetType: AssetType.PresentationSlide,
    category: 'premium',
    background: { type: 'solid', value: '#F4F7FB' },
    dimensions: SLIDE_16_9,
    fields: [
      text('title', 'Title', { x: 5, y: 7, width: 32, height: 12 }, { placeholder: 'Campaign system at a glance', required: true, style: { fontSize: 36, fontWeight: 'bold', color: '#0A1024', lineHeight: 1.08 } }),
      text('body', 'Narrative', { x: 5, y: 24, width: 28, height: 18 }, { placeholder: 'Use this slide to show a connected set of assets, campaign moments, or design variants.', style: { fontSize: 17, lineHeight: 1.5, color: '#4B587C' } }),
      divider('accent', 'Accent Divider', { x: 5, y: 48, width: 18, height: 0.45 }, '#139DD8'),
      logo('logo', 'Logo', { x: 5, y: 84, width: 12, height: 8 }),
      image('asset-1', 'Asset 1', { x: 40, y: 8, width: 24, height: 24 }, { placeholder: 'Drop asset', group: 'drag-drop-assets' }),
      image('asset-2', 'Asset 2', { x: 68, y: 8, width: 24, height: 24 }, { placeholder: 'Drop asset', group: 'drag-drop-assets' }),
      image('asset-3', 'Asset 3', { x: 40, y: 38, width: 16, height: 22 }, { placeholder: 'Drop asset', group: 'drag-drop-assets' }),
      image('asset-4', 'Asset 4', { x: 60, y: 38, width: 16, height: 22 }, { placeholder: 'Drop asset', group: 'drag-drop-assets' }),
      image('asset-5', 'Asset 5', { x: 80, y: 38, width: 12, height: 22 }, { placeholder: 'Drop asset', group: 'drag-drop-assets' }),
      image('asset-6', 'Asset 6', { x: 40, y: 67, width: 52, height: 22 }, { placeholder: 'Drop wide asset', group: 'drag-drop-assets' }),
    ],
    defaultFonts: { heading: 'Inter', body: 'Inter' },
    defaultColors: { primary: '#139DD8', secondary: '#E0E8F5', accent: '#003B71', text: '#0A1024', background: '#F4F7FB' },
    tags: ['presentation', 'portfolio', 'gallery', 'assets', 'drag-drop', 'premium'],
    colorMode: 'RGB',
    dpi: 72,
    isPremium: true,
    isSystemTemplate: true,
  },
  {
    id: 'pres-logo-safe-zone-master',
    name: 'Logo Safe-Zone Master',
    description: 'Brand governance slide with exact-logo drop zones, clear-space guides, and approval notes.',
    assetType: AssetType.PresentationSlide,
    category: 'premium',
    background: { type: 'gradient', value: 'linear-gradient(180deg, #FFFFFF 0%, #EEF4FA 100%)' },
    dimensions: SLIDE_16_9,
    fields: [
      text('title', 'Title', { x: 6, y: 7, width: 56, height: 8 }, { placeholder: 'Logo placement and safe-zone system', required: true, style: { fontSize: 34, fontWeight: 'bold', color: '#0A1024' } }),
      text('note', 'Guidance', { x: 6, y: 18, width: 58, height: 8 }, { placeholder: 'Drop exact approved logos only. Never redraw, distort, crop, or recolor source marks.', style: { fontSize: 17, lineHeight: 1.4, color: '#4B587C' } }),
      logo('primary-logo', 'Primary Logo Drop Zone', { x: 10, y: 38, width: 30, height: 18 }, { group: 'drag-drop-assets', placeholder: 'Drop primary logo' }),
      logo('reverse-logo', 'Reverse Logo Drop Zone', { x: 55, y: 38, width: 30, height: 18 }, { group: 'drag-drop-assets', placeholder: 'Drop reverse logo' }),
      text('clearspace-1', 'Clearspace Label 1', { x: 10, y: 60, width: 30, height: 5 }, { placeholder: 'Minimum clear space = 1x mark height', style: { fontSize: 13, color: '#003B71', textAlign: 'center' } }),
      text('clearspace-2', 'Clearspace Label 2', { x: 55, y: 60, width: 30, height: 5 }, { placeholder: 'Use only approved white / reverse mark', style: { fontSize: 13, color: '#003B71', textAlign: 'center' } }),
      icon('approved-icon', 'Approved Icon', { x: 10, y: 76, width: 4, height: 5 }, { group: 'drag-drop-assets' }),
      text('approved-copy', 'Approved Copy', { x: 15, y: 76, width: 30, height: 5 }, { placeholder: 'Approved placement', style: { fontSize: 15, fontWeight: 'bold', color: '#0A1024' } }),
      icon('warning-icon', 'Warning Icon', { x: 55, y: 76, width: 4, height: 5 }, { group: 'drag-drop-assets' }),
      text('warning-copy', 'Warning Copy', { x: 60, y: 76, width: 32, height: 5 }, { placeholder: 'Needs human review', style: { fontSize: 15, fontWeight: 'bold', color: '#0A1024' } }),
    ],
    defaultFonts: { heading: 'Inter', body: 'Inter' },
    defaultColors: { primary: '#003B71', secondary: '#E0E8F5', accent: '#139DD8', text: '#0A1024', background: '#FFFFFF' },
    tags: ['presentation', 'brand', 'logo', 'governance', 'safe-zone', 'drag-drop', 'premium'],
    colorMode: 'RGB',
    dpi: 72,
    isPremium: true,
    isSystemTemplate: true,
  },
  {
    id: 'pres-data-observatory',
    name: 'Data Observatory',
    description: 'Advanced data-story slide with chart placeholder, insight cards, icon signals, and source note.',
    assetType: AssetType.PresentationSlide,
    category: 'premium',
    background: { type: 'gradient', value: 'radial-gradient(circle at 24% 24%, rgba(123,205,58,0.22), transparent 28%), linear-gradient(135deg, #07111F 0%, #0C1E36 100%)' },
    dimensions: SLIDE_16_9,
    fields: [
      text('title', 'Title', { x: 6, y: 7, width: 52, height: 9 }, { placeholder: 'What the data is telling us', required: true, style: { fontSize: 38, fontWeight: 'bold' } }),
      text('subtitle', 'Subtitle', { x: 6, y: 18, width: 46, height: 6 }, { placeholder: 'Three signals that shape the next decision.', style: { fontSize: 17, color: 'rgba(255,255,255,0.62)' } }),
      image('chart-drop', 'Chart / Data Viz Drop Zone', { x: 6, y: 32, width: 54, height: 47 }, { placeholder: 'Drop chart image, dashboard screenshot, or exported data visual', group: 'drag-drop-assets', aspectRatio: 1.8 }),
      icon('signal-1-icon', 'Signal 1 Icon', { x: 67, y: 28, width: 4, height: 5 }, { group: 'drag-drop-assets' }),
      text('signal-1', 'Signal 1', { x: 73, y: 27, width: 19, height: 8 }, { placeholder: 'Demand is accelerating', style: { fontSize: 18, fontWeight: 'bold' } }),
      icon('signal-2-icon', 'Signal 2 Icon', { x: 67, y: 45, width: 4, height: 5 }, { group: 'drag-drop-assets' }),
      text('signal-2', 'Signal 2', { x: 73, y: 44, width: 19, height: 8 }, { placeholder: 'Quality remains stable', style: { fontSize: 18, fontWeight: 'bold' } }),
      icon('signal-3-icon', 'Signal 3 Icon', { x: 67, y: 62, width: 4, height: 5 }, { group: 'drag-drop-assets' }),
      text('signal-3', 'Signal 3', { x: 73, y: 61, width: 19, height: 8 }, { placeholder: 'Speed is the constraint', style: { fontSize: 18, fontWeight: 'bold' } }),
      text('source', 'Source Note', { x: 6, y: 85, width: 54, height: 4 }, { placeholder: 'Source: Q4 dashboard export / internal analysis', style: { fontSize: 11, color: 'rgba(255,255,255,0.42)' } }),
    ],
    defaultFonts: { heading: 'Inter', body: 'Inter' },
    defaultColors: { primary: '#7BCD3A', secondary: '#0C1E36', accent: '#139DD8', text: '#ffffff', background: '#07111F' },
    tags: ['presentation', 'data', 'dashboard', 'chart', 'drag-drop', 'premium'],
    colorMode: 'RGB',
    dpi: 72,
    isPremium: true,
    isSystemTemplate: true,
  },
  {
    id: 'pres-resource-qr-cta',
    name: 'Resource QR CTA',
    description: 'Closing slide with QR/resource drop zone, supporting device mockup, and clear CTA hierarchy.',
    assetType: AssetType.PresentationSlide,
    category: 'premium',
    background: { type: 'gradient', value: 'linear-gradient(135deg, #003B71 0%, #139DD8 46%, #03002C 100%)' },
    dimensions: SLIDE_16_9,
    fields: [
      logo('logo', 'Logo', { x: 5, y: 5, width: 12, height: 8 }),
      text('title', 'CTA Title', { x: 7, y: 28, width: 42, height: 14 }, { placeholder: 'Get the full resource kit', required: true, style: { fontSize: 48, fontWeight: 'bold', lineHeight: 1.05 } }),
      text('subtitle', 'CTA Subtitle', { x: 7, y: 48, width: 38, height: 10 }, { placeholder: 'Scan to download the templates, examples, and next-step checklist.', style: { fontSize: 20, lineHeight: 1.45, color: 'rgba(255,255,255,0.72)' } }),
      qr('qr-code', 'QR Code / URL', { x: 8, y: 68, width: 13, height: 20 }, { group: 'drag-drop-assets' }),
      text('url', 'Short URL', { x: 24, y: 75, width: 30, height: 6 }, { placeholder: 'brand.com/resource-kit', style: { fontSize: 18, fontWeight: 'bold', color: '#ffffff' } }),
      image('device-mockup', 'Device Mockup', { x: 57, y: 15, width: 34, height: 68 }, { placeholder: 'Drop phone/laptop mockup', group: 'drag-drop-assets', aspectRatio: 0.75 }),
    ],
    defaultFonts: { heading: 'Inter', body: 'Inter' },
    defaultColors: { primary: '#139DD8', secondary: '#003B71', accent: '#A1F9F9', text: '#ffffff', background: '#003B71' },
    tags: ['presentation', 'cta', 'qr', 'resource', 'drag-drop', 'premium'],
    colorMode: 'RGB',
    dpi: 72,
    isPremium: true,
    isSystemTemplate: true,
  },
];
