// Cutting-edge presentation slide templates — premium prebuilt page variations

import { EditableTemplate, TemplateField } from '@/types/editableTemplate.types';
import { AssetType } from '@/types';

const createPixelDimensions = (w: number, h: number) => ({
  widthInches: w / 72,
  heightInches: h / 72,
  widthPx: w,
  heightPx: h,
  bleedInches: 0,
  safeZoneInches: 0,
  orientation: (w > h ? 'landscape' : h > w ? 'portrait' : 'square') as 'portrait' | 'landscape' | 'square',
});

const createTextField = (
  id: string,
  name: string,
  position: TemplateField['position'],
  options: Partial<Omit<TemplateField, 'id' | 'name' | 'type' | 'position'>> = {},
): TemplateField => ({
  id,
  name,
  type: 'text',
  position,
  style: {
    fontFamily: 'Inter',
    fontSize: 14,
    fontWeight: 'normal',
    textAlign: 'left',
    color: '#ffffff',
    ...options.style,
  },
  ...options,
});

const createLogoField = (
  id: string,
  name: string,
  position: TemplateField['position'],
  options: Partial<Omit<TemplateField, 'id' | 'name' | 'type' | 'position'>> = {},
): TemplateField => ({
  id,
  name,
  type: 'logo',
  position,
  style: { objectFit: 'contain', ...options.style },
  acceptedFormats: ['png', 'svg'],
  ...options,
});

const createImageField = (
  id: string,
  name: string,
  position: TemplateField['position'],
  options: Partial<Omit<TemplateField, 'id' | 'name' | 'type' | 'position'>> = {},
): TemplateField => ({
  id,
  name,
  type: 'image',
  position,
  style: { objectFit: 'cover', borderRadius: 0, ...options.style },
  acceptedFormats: ['jpg', 'png', 'webp'],
  ...options,
});

const SLIDE_16_9 = createPixelDimensions(1920, 1080);

export const CUTTING_EDGE_PRESENTATION_TEMPLATES: EditableTemplate[] = [
  {
    id: 'pres-ai-command-center',
    name: 'AI Command Center',
    description: 'Dark executive dashboard slide with glowing command-card system and KPI rail.',
    assetType: AssetType.PresentationSlide,
    category: 'premium',
    background: {
      type: 'gradient',
      value: 'radial-gradient(circle at 18% 18%, rgba(19,157,216,0.36) 0%, transparent 32%), radial-gradient(circle at 82% 8%, rgba(115,86,192,0.42) 0%, transparent 30%), linear-gradient(135deg, #03002C 0%, #08143F 48%, #03002C 100%)',
    },
    dimensions: SLIDE_16_9,
    fields: [
      createLogoField('logo', 'Logo', { x: 5, y: 5, width: 10, height: 7 }, { placeholder: 'Logo' }),
      createTextField('eyebrow', 'Eyebrow', { x: 7, y: 17, width: 30, height: 5 }, { placeholder: 'AI OPERATING SYSTEM', style: { fontSize: 14, fontWeight: 'bold', letterSpacing: 4, color: '#A1F9F9' } }),
      createTextField('title', 'Title', { x: 7, y: 25, width: 48, height: 18 }, { placeholder: 'Command center for global content operations', required: true, style: { fontSize: 50, fontWeight: 'bold', lineHeight: 1.05, color: '#ffffff' } }),
      createTextField('body', 'Body', { x: 7, y: 48, width: 38, height: 20 }, { placeholder: 'Coordinate strategy, localization, quality, analytics, and delivery from a single intelligent workflow.', style: { fontSize: 19, lineHeight: 1.55, color: 'rgba(255,255,255,0.76)' } }),
      createTextField('metric1', 'Metric 1', { x: 7, y: 76, width: 17, height: 10 }, { placeholder: '42%', style: { fontSize: 42, fontWeight: 'bold', color: '#139DD8' } }),
      createTextField('metric1-label', 'Metric 1 Label', { x: 7, y: 87, width: 17, height: 5 }, { placeholder: 'Faster cycles', style: { fontSize: 13, color: 'rgba(255,255,255,0.58)' } }),
      createTextField('card1', 'Command Card 1', { x: 58, y: 18, width: 30, height: 8 }, { placeholder: '01  Strategy Intake', style: { fontSize: 18, fontWeight: 'bold', color: '#ffffff' } }),
      createTextField('card2', 'Command Card 2', { x: 63, y: 34, width: 30, height: 8 }, { placeholder: '02  Brand Brain QA', style: { fontSize: 18, fontWeight: 'bold', color: '#ffffff' } }),
      createTextField('card3', 'Command Card 3', { x: 58, y: 50, width: 30, height: 8 }, { placeholder: '03  Human Review', style: { fontSize: 18, fontWeight: 'bold', color: '#ffffff' } }),
      createTextField('card4', 'Command Card 4', { x: 63, y: 66, width: 30, height: 8 }, { placeholder: '04  Export Ready', style: { fontSize: 18, fontWeight: 'bold', color: '#ffffff' } }),
    ],
    defaultFonts: { heading: 'Inter', body: 'Inter' },
    defaultColors: { primary: '#139DD8', secondary: '#003B71', accent: '#A1F9F9', text: '#ffffff', background: '#03002C' },
    tags: ['presentation', 'ai', 'dashboard', 'command-center', 'premium', 'executive'],
    colorMode: 'RGB',
    dpi: 72,
    isPremium: true,
    isSystemTemplate: true,
  },
  {
    id: 'pres-master-hero-orb',
    name: 'Master Hero Orb',
    description: 'Cinematic master-title slide with oversized atmospheric orb and editorial title stack.',
    assetType: AssetType.PresentationSlide,
    category: 'premium',
    background: { type: 'gradient', value: 'radial-gradient(circle at 72% 44%, rgba(161,249,249,0.52) 0%, rgba(115,86,192,0.28) 24%, transparent 45%), linear-gradient(120deg, #03002C 0%, #051248 58%, #071C52 100%)' },
    dimensions: SLIDE_16_9,
    fields: [
      createLogoField('logo', 'Logo', { x: 5, y: 5, width: 10, height: 7 }, { placeholder: 'Logo' }),
      createTextField('section', 'Section Label', { x: 7, y: 18, width: 35, height: 5 }, { placeholder: 'MASTER SLIDE SYSTEM', style: { fontSize: 13, fontWeight: 'bold', letterSpacing: 4, color: '#A1F9F9' } }),
      createTextField('title', 'Title', { x: 7, y: 28, width: 50, height: 24 }, { placeholder: 'Transforming global performance', required: true, style: { fontSize: 68, fontWeight: 'bold', lineHeight: 0.95, color: '#ffffff' } }),
      createTextField('subtitle', 'Subtitle', { x: 7, y: 61, width: 42, height: 10 }, { placeholder: 'A premium keynote system built for momentum, clarity, and scale.', style: { fontSize: 22, lineHeight: 1.45, color: 'rgba(255,255,255,0.72)' } }),
      createTextField('footer', 'Footer', { x: 7, y: 88, width: 36, height: 4 }, { placeholder: '2026 / EXECUTIVE PRESENTATION', style: { fontSize: 12, letterSpacing: 3, color: 'rgba(255,255,255,0.48)' } }),
    ],
    defaultFonts: { heading: 'Inter', body: 'Inter' },
    defaultColors: { primary: '#139DD8', secondary: '#7356C0', accent: '#A1F9F9', text: '#ffffff', background: '#03002C' },
    tags: ['presentation', 'master-slide', 'hero', 'orb', 'keynote', 'premium'],
    colorMode: 'RGB',
    dpi: 72,
    isPremium: true,
    isSystemTemplate: true,
  },
  {
    id: 'pres-case-study-cinematic',
    name: 'Cinematic Case Study',
    description: 'Modern case-study slide with image panel, results stack, and narrative pull quote.',
    assetType: AssetType.PresentationSlide,
    category: 'premium',
    background: { type: 'solid', value: '#08101F' },
    dimensions: SLIDE_16_9,
    fields: [
      createImageField('hero-image', 'Hero Image', { x: 0, y: 0, width: 46, height: 100 }, { placeholder: 'Case study image' }),
      createTextField('eyebrow', 'Eyebrow', { x: 52, y: 10, width: 34, height: 5 }, { placeholder: 'CASE STUDY', style: { fontSize: 13, fontWeight: 'bold', letterSpacing: 4, color: '#3BBFB5' } }),
      createTextField('title', 'Title', { x: 52, y: 19, width: 40, height: 15 }, { placeholder: 'How a global launch moved faster', required: true, style: { fontSize: 42, fontWeight: 'bold', lineHeight: 1.1, color: '#ffffff' } }),
      createTextField('story', 'Story', { x: 52, y: 39, width: 38, height: 18 }, { placeholder: 'A concise narrative of the challenge, solution, and measurable business outcome.', style: { fontSize: 18, lineHeight: 1.55, color: 'rgba(255,255,255,0.72)' } }),
      createTextField('result1', 'Result 1', { x: 52, y: 66, width: 14, height: 10 }, { placeholder: '3.4x', style: { fontSize: 40, fontWeight: 'bold', color: '#139DD8' } }),
      createTextField('result1-label', 'Result 1 Label', { x: 52, y: 77, width: 14, height: 5 }, { placeholder: 'Output lift', style: { fontSize: 12, color: 'rgba(255,255,255,0.55)' } }),
      createTextField('result2', 'Result 2', { x: 70, y: 66, width: 14, height: 10 }, { placeholder: '28%', style: { fontSize: 40, fontWeight: 'bold', color: '#3BBFB5' } }),
      createTextField('result2-label', 'Result 2 Label', { x: 70, y: 77, width: 18, height: 5 }, { placeholder: 'Cost reduction', style: { fontSize: 12, color: 'rgba(255,255,255,0.55)' } }),
      createLogoField('logo', 'Logo', { x: 86, y: 88, width: 9, height: 7 }, { placeholder: 'Logo' }),
    ],
    defaultFonts: { heading: 'Inter', body: 'Inter' },
    defaultColors: { primary: '#139DD8', secondary: '#08101F', accent: '#3BBFB5', text: '#ffffff', background: '#08101F' },
    tags: ['presentation', 'case-study', 'cinematic', 'results', 'premium'],
    colorMode: 'RGB',
    dpi: 72,
    isPremium: true,
    isSystemTemplate: true,
  },
  {
    id: 'pres-roadmap-neon-rail',
    name: 'Neon Roadmap Rail',
    description: 'Cutting-edge roadmap slide with glowing horizontal rail and milestone cards.',
    assetType: AssetType.PresentationSlide,
    category: 'premium',
    background: { type: 'gradient', value: 'linear-gradient(135deg, #06091A 0%, #10183A 52%, #03002C 100%)' },
    dimensions: SLIDE_16_9,
    fields: [
      createTextField('title', 'Title', { x: 6, y: 8, width: 52, height: 10 }, { placeholder: 'Roadmap to launch', required: true, style: { fontSize: 42, fontWeight: 'bold', color: '#ffffff' } }),
      createTextField('subtitle', 'Subtitle', { x: 6, y: 20, width: 46, height: 6 }, { placeholder: 'Four focused phases from intake to global scale.', style: { fontSize: 18, color: 'rgba(255,255,255,0.62)' } }),
      createTextField('phase1', 'Phase 1', { x: 8, y: 45, width: 18, height: 14 }, { placeholder: '01\nDiscover', style: { fontSize: 24, fontWeight: 'bold', color: '#A1F9F9', lineHeight: 1.35 } }),
      createTextField('phase2', 'Phase 2', { x: 31, y: 36, width: 18, height: 14 }, { placeholder: '02\nDesign', style: { fontSize: 24, fontWeight: 'bold', color: '#139DD8', lineHeight: 1.35 } }),
      createTextField('phase3', 'Phase 3', { x: 54, y: 45, width: 18, height: 14 }, { placeholder: '03\nBuild', style: { fontSize: 24, fontWeight: 'bold', color: '#7356C0', lineHeight: 1.35 } }),
      createTextField('phase4', 'Phase 4', { x: 77, y: 36, width: 18, height: 14 }, { placeholder: '04\nScale', style: { fontSize: 24, fontWeight: 'bold', color: '#EC388A', lineHeight: 1.35 } }),
      createTextField('note', 'Note', { x: 7, y: 82, width: 55, height: 6 }, { placeholder: 'Each milestone includes owner, timing, output, and success criteria.', style: { fontSize: 16, color: 'rgba(255,255,255,0.56)' } }),
      createLogoField('logo', 'Logo', { x: 87, y: 7, width: 8, height: 6 }, { placeholder: 'Logo' }),
    ],
    defaultFonts: { heading: 'Inter', body: 'Inter' },
    defaultColors: { primary: '#139DD8', secondary: '#7356C0', accent: '#EC388A', text: '#ffffff', background: '#06091A' },
    tags: ['presentation', 'roadmap', 'neon', 'timeline', 'premium'],
    colorMode: 'RGB',
    dpi: 72,
    isPremium: true,
    isSystemTemplate: true,
  },
  {
    id: 'pres-executive-decision-grid',
    name: 'Executive Decision Grid',
    description: 'Premium executive summary slide with decision cards, risk signals, and recommendation band.',
    assetType: AssetType.PresentationSlide,
    category: 'premium',
    background: { type: 'gradient', value: 'linear-gradient(180deg, #F7F9FC 0%, #E9EEF7 100%)' },
    dimensions: SLIDE_16_9,
    fields: [
      createLogoField('logo', 'Logo', { x: 5, y: 5, width: 10, height: 7 }, { placeholder: 'Logo' }),
      createTextField('title', 'Title', { x: 7, y: 15, width: 58, height: 10 }, { placeholder: 'Executive decision summary', required: true, style: { fontSize: 42, fontWeight: 'bold', color: '#0A1024' } }),
      createTextField('recommendation', 'Recommendation', { x: 7, y: 30, width: 86, height: 10 }, { placeholder: 'Recommended path: consolidate workflows into one governed launch system.', style: { fontSize: 24, fontWeight: 'bold', color: '#003B71' } }),
      createTextField('card1', 'Decision Card 1', { x: 7, y: 50, width: 25, height: 17 }, { placeholder: 'Impact\nHigh revenue upside', style: { fontSize: 21, fontWeight: 'bold', color: '#0A1024', lineHeight: 1.35 } }),
      createTextField('card2', 'Decision Card 2', { x: 37, y: 50, width: 25, height: 17 }, { placeholder: 'Effort\nModerate lift', style: { fontSize: 21, fontWeight: 'bold', color: '#0A1024', lineHeight: 1.35 } }),
      createTextField('card3', 'Decision Card 3', { x: 67, y: 50, width: 25, height: 17 }, { placeholder: 'Risk\nControlled with QA', style: { fontSize: 21, fontWeight: 'bold', color: '#0A1024', lineHeight: 1.35 } }),
      createTextField('footer', 'Footer Note', { x: 7, y: 82, width: 72, height: 6 }, { placeholder: 'Decision needed today: approve the recommended path and resourcing model.', style: { fontSize: 16, color: '#4B587C' } }),
    ],
    defaultFonts: { heading: 'Inter', body: 'Inter' },
    defaultColors: { primary: '#003B71', secondary: '#E0E8F5', accent: '#139DD8', text: '#0A1024', background: '#F7F9FC' },
    tags: ['presentation', 'executive', 'decision', 'summary', 'premium'],
    colorMode: 'RGB',
    dpi: 72,
    isPremium: true,
    isSystemTemplate: true,
  },
];
